-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1:3306
-- Время создания: Июн 05 2020 г., 17:24
-- Версия сервера: 5.7.23
-- Версия PHP: 7.2.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `phpshop`
--

-- --------------------------------------------------------

--
-- Структура таблицы `product`
--

CREATE TABLE `product` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `price` float NOT NULL,
  `availability` int(11) NOT NULL,
  `description` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `product`
--

INSERT INTO `product` (`id`, `name`, `price`, `availability`, `description`) VALUES
(1, 'Product 1', 390, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(2, 'Product 2', 305, 0, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(3, 'Product 3', 270, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(4, 'Product 4', 325, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(5, 'Product 5', 275, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(6, 'Product 6', 370, 0, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(7, 'Product 7', 430, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(8, 'Product 8', 780, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(9, 'Product 9', 640, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(10, 'Product 10', 210, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(11, 'Product 11', 175, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(12, 'Product 12', 1320, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(13, 'Product 13', 390, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(14, 'Product 14', 305, 0, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(15, 'Product 15', 270, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(16, 'Product 16', 325, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(17, 'Product 17', 275, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(18, 'Product 18', 370, 0, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(19, 'Product 19', 430, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(20, 'Product 20', 780, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(21, 'Product 21', 640, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(22, 'Product 22', 210, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(23, 'Product 23', 175, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(24, 'Product 24', 1320, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(25, 'Product 25', 390, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(26, 'Product 26', 305, 0, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(27, 'Product 27', 270, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(28, 'Product 28', 325, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(29, 'Product 29', 275, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(30, 'Product 30', 370, 0, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(31, 'Product 31', 430, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(32, 'Product 32', 780, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(33, 'Product 33', 640, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(34, 'Product 34', 210, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(35, 'Product 35', 175, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(36, 'Product 36', 1320, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(37, 'Product 37', 390, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(38, 'Product 38', 305, 0, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(39, 'Product 39', 270, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(40, 'Product 40', 325, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(41, 'Product 41', 275, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(42, 'Product 42', 370, 0, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(43, 'Product 43', 430, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(44, 'Product 44', 780, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(45, 'Product 45', 640, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(46, 'Product 46', 210, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(47, 'Product 47', 175, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(48, 'Product 48', 1320, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(49, 'Product 49', 370, 0, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(50, 'Product 50', 430, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(51, 'Product 51', 780, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(52, 'Product 52', 640, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(53, 'Product 53', 210, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(54, 'Product 54', 175, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.'),
(55, 'Product 55', 1320, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, atque, similique, optio illum modi deleniti impedit dignissimos perferendis blanditiis provident reiciendis quam nostrum labore facilis architecto iste quasi odit mollitia dolore non tempore recusandae cumque molestiae maxime esse necessitatibus at iusto ipsam quas tempora iure eveniet voluptatem vel? Velit, sit, excepturi error voluptatibus cupiditate deleniti iure consequatur tempore molestias ipsum asperiores voluptates assumenda minus esse quidem cum earum qui! Officia, tempore sint nobis expedita quis facilis nostrum accusamus veniam ratione eveniet. Laudantium, facilis, dignissimos, quo, consectetur velit eaque nobis impedit delectus asperiores earum voluptate labore excepturi doloremque hic error cumque.');

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `product`
--
ALTER TABLE `product`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `product`
--
ALTER TABLE `product`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=56;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
